app:
  udp-port: ${UDP_PORT}
  sensor-type: ${SENSOR_TYPE}
  topics:
    sensor-inputs-topic: ${SENSOR_INPUTS_TOPIC_NAME}

spring:
  application:
    name: warehouse-service
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
